repos:

# Use seed-isort-config to generate the known_third_party list in
# pyproject.toml. This is not active by default for speed concerns.
# -   repo: https://github.com/asottile/seed-isort-config
#     rev: v2.2.0
#     hooks:
#     - id: seed-isort-config

-   repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
    - id: isort

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
