version: "2"
services:
  linotp:
    image: linotp:latest
    environment:
      LINOTP_DATABASE_URI: "postgres://linotpuser:linotppass@linotp-db/linotp_db"
      LINOTP_DB_HOST: "linotp-db"
      LINOTP_DB_PORT: "5432"
      HEALTHCHECK_PORT: "80"
      SSL_TRUSTED_CERT: "
      Issuer: O = LinOTP-DE, CN = LinOTP-DE Root CA
        Validity
            Not Before: Feb  6 12:15:37 2022 GMT
            Not After : Feb  4 12:15:37 2032 GMT
        Subject: O = LinOTP-DE, CN = LinOTP-DE Root CA
      -----BEGIN CERTIFICATE-----
      MIIBojCCAUmgAwIBAgIQPlwfzlZDQsPhD1rWE9Ux3TAKBggqhkjOPQQDAjAwMRIw
      EAYDVQQKEwlMaW5PVFAtREUxGjAYBgNVBAMTEUxpbk9UUC1ERSBSb290IENBMB4X
      DTIyMDIwNjEyMTUzN1oXDTMyMDIwNDEyMTUzN1owMDESMBAGA1UEChMJTGluT1RQ
      LURFMRowGAYDVQQDExFMaW5PVFAtREUgUm9vdCBDQTBZMBMGByqGSM49AgEGCCqG
      SM49AwEHA0IABGZPiX58lcLz+oX/CNZFdJI3bWE9KdxRlmypYWwbZUqkhLn1ARWc
      lblmltOU/L6/XlbYuLWdTE3Hk1VF7UA+zdejRTBDMA4GA1UdDwEB/wQEAwIBBjAS
      BgNVHRMBAf8ECDAGAQH/AgEBMB0GA1UdDgQWBBRY28kvC11GjduDBsUaQvIr87ke
      MDAKBggqhkjOPQQDAgNHADBEAiB9pumbZbFk5ChludETNKxFzSVRCx7Cbzm1zNCw
      TGfofQIgFClkyscaKq+ALGjKzDAf+oF4A1BgOzqdFxafFePRH54=
      -----END CERTIFICATE-----
      "
    depends_on:
      - linotp-db
    ports:
      - "443:443"
    expose:
      - "80"

  linotp-db:
    image: postgres:latest
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: "linotp_db"
      POSTGRES_PASSWORD: "linotppass"
      POSTGRES_USER: "linotpuser"
    volumes:
    - /var/lib/postgresql/data/pgdata
