[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 79
known_third_party = [
  "Cryptodome",
  "beaker",
  "click",
  "configobj",
  "cryptography",
  "flaky",
  "flask_babel",
  "flask_sqlalchemy",
  "freezegun",
  "httplib2",
  "integration_data",
  "jsonschema",
  "ldap",
  "mako",
  "mock",
  "mockldap",
  "netaddr",
  "passlib",
  "paste",
  "pkg_resources",
  "pyrad",
  "pysodium",
  "pytest",
  "pytest_testconfig",
  "qrcode",
  "requests",
  "selenium",
  "setuptools",
  "sqlalchemy",
  "urllib3",
  "webhelpers",
  "werkzeug",
]
known_flask = [
  "flask",
]
known_first_party = [
  "linotp",
  "linotp_selenium_helper",
]
sections = [
  "FUTURE",
  "STDLIB",
  "THIRDPARTY",
  "FLASK",
  "FIRSTPARTY",
  "LOCALFOLDER",
]
