#!/bin/bash -e
. /usr/share/debconf/confmodule

db_input high linotp/apache/activate || true
db_go
db_get linotp/apache/activate
APACHE=$RET

dbc_dbtypes="mysql, pgsql"
if [ "$APACHE" = "true" ]; then
  db_input high linotp/apache/admin_password || true
  db_go

  db_input high linotp/apache/ssl_create || true
  db_go
else
  # If not using apache, you can also choose SQLlite
  dbc_dbtypes="$dbc_dbtypes, sqlite"
fi

# Database configuration using dbconfig-common
if [ -f /usr/share/dbconfig-common/dpkg/config ]; then
  # Load library
  . /usr/share/dbconfig-common/dpkg/config

  # Define default values for database
  #dbc_authmethod_user="password"

  # Script to import intial settings from previous packaging
  dbc_load_include=exec:/usr/share/dbconfig-common/scripts/linotp/dbconfig-vars
  dbc_first_version="3.0~a1"


  # Ask questions
  dbc_go linotp "$@"
fi
