#!/bin/sh -e

if [ -f /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
fi
if [ -f /usr/share/dbconfig-common/dpkg/postrm ]; then
	. /usr/share/dbconfig-common/dpkg/postrm
	dbc_go linotp "$@"
fi

print_timestamp() {
	date +"%Y/%m/%d - %T"
}

if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
    # Source debconf library.
    . /usr/share/debconf/confmodule
    # Remove my changes to the db.
    db_purge
    if getent passwd linotp > /dev/null; then
	if ! a2dissite linotp; then
	    echo `print_timestamp` "WARNING [linotp postrm] Could not disable Apache linotp host (possibly it doesn't exist)" >&2
	elif ! invoke-rc.d apache2 reload 2>/dev/null; then
	    echo `print_timestamp` "WARNING [linotp postrm] Could not reload Apache (may not be a problem)"
	fi
	echo "Deleting user >>linotp<<"
	deluser linotp
    fi
    echo "Deleting log directory."
    rm -fr /var/log/linotp

    # Where I come from, “purge” means purge.
    rm -rf /etc/linotp/*
fi

#DEBHELPER#
