#!/bin/sh

set -e

if [ "$1" = "upgrade" ]; then
	# If user supplied stylesheets were placed under /usr/share/, move these
	# to /etc/custom-style.
	#
	# We do this in preinst to allow dpkg a chance to remove the old directories.
	# Any files left over will trigger a warning message
	if dpkg --compare-versions "$2" lt "2.10.0.3~0"; then
		# Upgrade from befre 2.10.0.3 - migrate older files
		for root in /usr/share/pyshared /usr/lib/pymodules/python2.7; do

			for controller in openid selfservice manage; do
				oldfile=$root/linotp/public/$controller/custom-style.css

				if [ -L $oldfile ]; then
					echo "Removing old symlink: $oldfile"
					rm $oldfile || exit 1
				elif [ -f $oldfile ]; then
					newfile=/etc/linotp/custom-style/$controller-style.css
					echo "Moving custom file $oldfile -> $newfile"
					mkdir -p /etc/linotp/custom-style || exit 1
					mv $oldfile $newfile || exit 1
				fi
			done
		done
	fi

	if dpkg --compare-versions "$2" lt "3.0~"; then
		available=/etc/apache2/sites-available
		enabled=/etc/apache2/sites-enabled
		if [ -f $available/linotp2.conf ]
		  then
			if cmp $available/linotp2.conf /etc/linotp2/apache2.4-example/linotp2.conf; then
				echo "Removing old Apache configuration"
				rm -f $available/linotp2.conf
			else
				echo "WARNING: Modified Apache site configuration found in $available/linotp2.conf"
				echo "This will no longer be used."
			fi
			rm -f $enabled/linotp2.conf

		fi # -f $available/linotp2.conf

		# If there is an /etc/linotp2 directory and no /etc/linotp directory,
		# then move /etc/linotp2 to /etc/linotp.
		if [ -d /etc/linotp2 ] && [ ! -d /etc/linotp ]; then
			echo "Moving LinOTP config directory from /etc/linotp2 to /etc/linotp"
			mv /etc/linotp2 /etc/linotp
		fi

		# Migrate Audit key
		CONFIG_DIR=/etc/linotp
		OLD_PRIVKEY="$CONFIG_DIR"/private.pem
		OLD_PUBKEY="$CONFIG_DIR"/public.pem
		PRIVKEY="$CONFIG_DIR"/audit-private.pem
		PUBKEY="$CONFIG_DIR"/audit-public.pem
		if [ -f "$OLD_PRIVKEY" -a ! -f "$PRIVKEY" ]; then
			# We have an old key pair that should be moved, lest people
			# lose access to their existing audit log.
			echo "Moving $OLD_PRIVKEY to $PRIVKEY"
			mv "$OLD_PRIVKEY" "$PRIVKEY"
			rm -f "$OLD_PUBKEY"	# no longer required

			# Extract the public key from the private key. We do this even
			# when we have copied an old private key, to be very sure that
			# the public key matches the private key.
			openssl rsa -in "$PRIVKEY" -pubout -out "$PUBKEY"
		fi

	fi # dpkg --compare-versions "$2" lt "3.0~"
fi # "$1" = "upgrade"

#DEBHELPER#
