#!/bin/sh

mkdir -p /etc/linotp2

if [ "$1" = "upgrade" ]; then
	touch /etc/linotp2/we_are_doing_an_upgrade

	# If user supplied stylesheets were placed under /usr/share/, move these
	# to /etc/custom-style.
	#
	# We do this in preinst to allow dpkg a chance to remove the old directories.
	# Any files left over will trigger a warning message
	if dpkg --compare-versions "$2" lt "2.10.0.3~0"; then
		# Upgrade from befre 2.10.0.3 - migrate older files
		for root in /usr/share/pyshared /usr/lib/pymodules/python2.7; do

			for controller in openid selfservice manage; do
				oldfile=$root/linotp/public/$controller/custom-style.css

				if [ -L $oldfile ]; then
					echo "Removing old symlink: $oldfile"
					rm $oldfile || exit 1
				elif [ -f $oldfile ]; then
					newfile=/etc/linotp2/custom-style/$controller-style.css
					echo "Moving custom file $oldfile -> $newfile"
					mkdir -p /etc/linotp2/custom-style || exit 1
					mv $oldfile $newfile || exit 1
				fi
			done
		done
	fi
fi

#DEBHELPER#
