#!/bin/sh -e

. /usr/share/debconf/confmodule
. /usr/share/dbconfig-common/dpkg/prerm
dbc_go linotp "$@"

print_timestamp() {
	date +"%Y/%m/%d - %T"
}

# check if linotp was run via apache
db_get linotp/apache/activate || true

if [ "$RET" = "true" ]; then
    if ! a2dissite linotp; then
	echo `print_timestamp` "WARNING [linotp prerm] Could not disable Apache linotp host (possibly it doesn't exist)" >&2
    elif ! invoke-rc.d apache2 reload 2>/dev/null; then
	echo `print_timestamp` "WARNING [linotp prerm] Could not reload Apache (may not be a problem)"
    fi
fi

#DEBHELPER#
