#!/bin/sh
set -e
# Automatically added by dh_pysupport
if which update-python-modules >/dev/null 2>&1; then
        update-python-modules linotp-adminclient-gui.public
fi

# End automatically added section

. /usr/share/debconf/confmodule
