#!/bin/bash
#
# LinOTP - the Open Source solution for multi-factor authentication
#
# Coypright © 2020- arxes-tolina GmbH
#
# Shell script based installation / upgrade / configuration tests
#

show_help() {
    echo
    echo "$0 TEST"
    echo
    echo " install2       Purge, install v2, selenium test"
    echo " install3       Purge, install v3"
    echo " upgrade2to3    Purge, install v2, upgrade to v3"
    echo " install3psql   Purge, install using postgres database"
    echo
    echo " upgrade3       Upgrade currently installed package to v3"
    echo " 3reinstall     Install v3 then reinstall v3"
    echo " remove         Remove installed package"
    echo
    echo " selenium_check Selenium test currently installed package"
    echo " mysql_password Check v3 install with password containing spaces"
    echo " htpasswd       Check admin password can be changed"
    echo " noapache       Install / reconfigure with apache disabled"
    echo
    echo " alltests       Run all available tests"
    echo " help           Show this help message"
    echo
}

# Exit on errors, unset variables or pipeline errors
set -euo pipefail


# Load environment from .env file
toolsdir="$(cd $(dirname $0); pwd)"
envfile="$toolsdir/.env"
if [ -f "$envfile" ]; then
  source "$envfile"
else
  echo "Using default settings. To customise for your environment, copy"
  echo "the file env.template to .env and edit for your local configuration"
fi

####
# Default settings that can be overriden from .env file or environment
####
# Sources directory
: "${linotp_project:="$(realpath "$toolsdir"/../../../../..)"}"

# config file for integration tests
: "${integration_ini="$(realpath ../integration/server_local.ini)"}"

# Command to gain root
: "${sudo="sudo --preserve-env=DEBIAN_FRONTEND,DEBIAN_PRIORITY"}"

# Pytest for running tests
: "${pytest="pytest"}"
####

# LinOTP 2 package to download and install
linotp2_deb_url="http://www.linotp.org/apt/debian/dists/buster/linotp/all/linotp_2.11.2-1~bpo10+1_all.deb"

linotpsrc=$linotp_project/linotpd/src

# Use line based debconf frontend if any missing questions
# are encountered
export DEBIAN_FRONTEND=readline

# This is a flag to indicate if any non fatal errors were
# detected during the process
have_errors=

error() {
    # Show error message but do not exit immediately
    echo "ERROR: $@"
    have_errors=1
}

fatal() {
    # Show error message and exit
    echo "FATAL: $@"
    exit 1
}

cfgfail() {
    # Error in configuration file
    echo "--- linotp.cfg --"
    $sudo cat /etc/linotp/linotp.cfg
    echo "-----------------"
    echo
    echo "CONFIGURATION ERROR: $@"
    exit 1
}

logtest() {
    echo
    echo "======================"
    echo "TEST: $@"
    echo "======================"
}

linotp3_db_name() {
    # Parse linotp.cfg to get database name
    $sudo python3 -c "
from urllib.parse import urlsplit
from flask import Config
c=Config('/etc/linotp')
c.from_pyfile('linotp.cfg')
print(urlsplit(c['DATABASE_URI']).path.strip('/'))
"
}

installed_linotp_ver() {
    # echo 2 or 3, depending on installed version.
    # The cutoff is actually 2.80
    if dpkg --compare-versions `dpkg-query -Wf '${Version}' linotp` ge "2.80"; then
        echo 3
    else
        echo 2
    fi
}

# Purge existing linotp package
# WARNING: This will remove any existing
# linotp package
purge() {
    if [ "$LINOTP_PURGE_ALLOW" != "yes" ]; then
        echo "
A complete package purge is required but is not allowed.

If you wish to proceed, set the following variable:
    LINOTP_PURGE_ALLOW=yes

WARNING: this will DELETE any existing linotp configuration!
"
        fatal "Confirmation of purge required"
    fi

    error="error"

    if [ -f /var/lib/dpkg/info/linotp.list ]; then

        # Preseed database removal on linotp3
        if [ "$(installed_linotp_ver)" = 3 ]; then
            echo "Preseeding dbconfig-common removal"
            echo "linotp linotp/dbconfig-remove boolean true" | $sudo debconf-set-selections || true
            echo "linotp linotp/purge boolean true" | $sudo debconf-set-selections || true
        else
            # LinOTP 2 problems are not errors for v3 testing
            error="echo"
        fi
        echo "Purging linotp"
        sudo apt --yes purge linotp

        # Drop mysql users if they exist
        $sudo mysql --defaults-file=/etc/mysql/debian.cnf -e "DROP USER IF EXISTS linotp, linotp2;" || true
    fi

    # Check if all files are removed
    if [ -d /usr/lib/python3/dist-packages/linotp ];then
        $error "dist-packages/linotp not removed"
        find /usr/lib/python3/dist-packages/linotp -ls
        sudo rm -rf /usr/lib/python3/dist-packages/linotp
    fi

    for file_to_check in \
        /etc/apache2/sites-available/linotp.conf \
        /etc/apache2/sites-available/linotp2.conf \
        /etc/apache2/sites-enabled/linotp.conf \
        /etc/apache2/sites-enabled/linotp2.conf
    do
        if [ -f $file_to_check ]; then
            $error "File still present after purge: $file_to_check (removing)"
            # Remove it so that further tests can be run
            $sudo rm "$file_to_check"
        fi
    done

}

preseed_2() {
    echo "Preseeding linotp2 questions"
    (
        echo "linotp linotp/apache/activate boolean true"
        echo "linotp linotp/apache/admin_password password admin"
        echo "linotp linotp/apache/ssl_create boolean false"

        echo "linotp linotp/mysql/ask_rootpw password $mysql_root_password"
        echo "linotp linotp/tokendb/randompw boolean true"
        echo "linotp linotp/mysql/ask_createdb boolean true"
        echo "linotp linotp/mysql/ask_createtables boolean true"
    ) | $sudo debconf-set-selections

}

preseed_3() {
    echo "Preseeding linotp3 questions for MariaDB database"
    (
        echo "linotp linotp/apache/activate boolean true"
        echo "linotp linotp/apache/admin_password password admin"
        echo "linotp linotp/apache/ssl_create boolean false"
        echo "linotp linotp/dbconfig-install boolean true"
        echo "linotp linotp/dbconfig-upgrade boolean true"
        echo "linotp linotp/database-type    select  mysql"
        echo "linotp linotp/mysql/app-pass password DataB123!"
    ) | $sudo debconf-set-selections
}

preseed_3_for_upgrade() {
    echo "Preseeding linotp3 questions for LinOTP 3 upgrade"
    (
        echo "linotp linotp/dbconfig-upgrade boolean true"
    ) | $sudo debconf-set-selections
}

preseed_3_postgres() {
    echo "Preseeding linotp3 questions for Postgres database"
    preseed_3
    (
        echo "linotp linotp/database-type    select  pgsql"
        echo "linotp  linotp/remote/host      select  localhost"
        echo "linotp linotp/pgsql/app-pass password DataBPG123!"
    ) | $sudo debconf-set-selections

}

install_2() {
    url="$1"
    linotp2_deb="$toolsdir"/"$(echo $url | grep -o "/[^/]*$")"
    if [ ! -f $linotp2_deb ]; then
        echo "Downloading linotp deb to $toolsdir"
        cd "$toolsdir"
        wget "$url"
    fi

    echo "Installing linotp 2 package"
    DEBIAN_PRIORITY=critical $sudo apt --yes install "$linotp2_deb" libapache2-mod-wsgi
}

install_3() {
    echo "Installing latest linotp 3 package"
    $sudo apt --yes install "$linotp3_deb" libapache2-mod-wsgi-py3
}

check_2() {
    echo "Testing to check we have a working linotp 2 install"
    check_service
    check_data_model_version "2.10.1.0"
}

check_3() {
    echo "Testing to see if all is okay and there are no known configuration problems"
    if $sudo grep -q "unconfigured" /etc/linotp/linotp.cfg; then
        cfgfail "SQLalchemy is not configured"
    fi
    # Mysql - check encoding
    if $sudo debconf-get-selections|grep -q "linotp\slinotp/database-type\sselect\smysql"; then
        if ! $sudo grep -q "charset=utf8" /etc/linotp/linotp.cfg; then
            cfgfail "Missing charset in linotp.cfg for mysql database"
        fi
    fi
    check_data_model_version "2.12.0.0"
    check_service
}
# sudo apt purge --yes linotp; sudo mysql --defaults-file=/etc/mysql/debian.cnf -e "DROP USER linotp;"; sudo debconf-set-selections config/linotp-with-mysql-preseed.txt && sudo debi

check_service() {
    # Check we can retrieve manage interface. This gives us an early indication if the install
    # did not work.
    # Param 1 is password (default: admin)
    local password=${1:-admin}
    echo "Retrieving manage interface page"
    if ! wget -nv --user=admin --password="$password" -O /dev/null --no-check-certificate https://localhost/manage; then
        echo "Apache error.log:"
        $sudo tail -n 10 /var/log/apache2/error.log
        fatal "Service is not working - cannot retrieve manage interface page"
    fi
}

check_data_model_version() {
    # Verify that data model version has been set properly. This gives us a quick check
    # to see whether database migrations have been applied
    expected_version=${1-2.10.1.0}
    if [ "$(installed_linotp_ver)" = 3 ]; then
        db="$(linotp3_db_name)"
    else
        # Don't try to guess it on the older packages
        db=LinOTP2
    fi
    sql="select Value from Config where Config.Key='linotp.sql_data_model_version'"
    cmd="mysql --defaults-file=/etc/mysql/debian.cnf -NB $db"
    echo "Checking model version"

    if ! model_version=$(echo "$sql" | $sudo $cmd); then
        echo "echo \"$sql\" |" "$sudo" "$cmd"
        fatal "Missing model version entry in database $db"
    fi

    if [ "$model_version" != "$expected_version" ]; then
        echo "echo \"$sql\" |" "$sudo" "$cmd"
        echo "Database $db error - found:$model_version expected:$expected_version"
        fatal "Model version incorrect"
    fi
}


selenium_check() {
    cd $linotpsrc/linotp/tests/integration
    if [ ! -f "$integration_ini" ]; then
        fatal "Could not find integration settings file: $(pwd)/$integration_ini"
    fi
    params="--tc-file=$integration_ini
        --tc=linotp.protocol:https
        --tc=linotp.port:443
        --tc=linotp.host:localhost
        --tc=linotp.username:admin
        --tc=linotp.password:admin
        -m smoketest"
    echo "$pytest $(echo "$params" | tr -d '\n')"
    "$pytest" $params
}

upgrade2to3() {
    # Purge, install 3, upgrade to 3
    purge
    logtest "Purge, install linotp 2, upgrade to linotp 3"
    echo "-- LinOTP 2 --"
    preseed_2
    install_2 "$linotp2_deb_url"
    echo "-- LinOTP 3 --"
    preseed_3_for_upgrade
    install_3
    check_3
}

install3() {
    purge
    logtest "Install linotp3 from scratch"
    preseed_3
    install_3
    check_3
}

upgrade3() {
    # Upgrade existing package to 3 without a fresh install first
    echo Lintop version to upgrade:
    dpkg-query --no-pager -l linotp | tail -1
    echo "-- LinOTP 3 upgrade --"
    preseed_3_for_upgrade
    install_3
    check_3
}

3reinstall() {
    logtest 3reinstall: Install fresh v3 instance and then reinstall it again
    install3
    upgrade3
}

mysql_password() {
    logtest "Install linotp3 from scratch"
    password="T.e.s.t.#123!"
    purge
    preseed_3
    echo "linotp linotp/mysql/app-pass password ${password}" | $sudo debconf-set-selections
    install_3
    check_3
    # Check mysql login is working
    logtest "Check mysql database access"
    dbc_dbname="$($sudo sh -c ". /etc/dbconfig-common/linotp.conf; echo \$dbc_dbname")"
    echo "select * from Config" | mysql --user=linotp --password="${password}" "$dbc_dbname"
}

install3psql() {
    purge
    logtest "Postgres install"
    preseed_3_postgres
    install_3
    check_3
}

dpkg_reconfigure() {
    # Reconfigure package using dpkg-reconfigure

    # Prerequestite: The relevant debconf questions
    # are already set

    cmd="dpkg-reconfigure -u linotp"
    echo "Executing $cmd"
    $sudo $cmd
}

htpasswd() {
    # Change login password using debconf interface

    purge
    logtest "Reconfigure testing"
    preseed_3
    install_3
    check_3
    logtest "Changing htpassword using debconf"
    (
        echo "linotp linotp/apache/activate boolean true"
        echo "linotp linotp/apache/admin_password password newpassword"
        echo "linotp  linotp/dbconfig-reinstall boolean false"
    ) | $sudo debconf-set-selections
    dpkg_reconfigure
    check_service "newpassword"

    echo "Test passed, resetting password back to admin"
    (
        echo "linotp linotp/apache/admin_password password admin"
    ) | $sudo debconf-set-selections
    dpkg_reconfigure
    check_service
}

noapache() {
    # Check package can be installed without apache, and
    # can be reconfigured to disable apache

    purge
    logtest "Install without apache"
    preseed_3
    (
        echo "linotp linotp/apache/activate boolean false"
    ) | $sudo debconf-set-selections
    install_3
    if ! wget -nv --user=admin --password=admin -O /dev/null --no-check-certificate https://localhost/manage; then
      echo "manage interface is unavailable as expected"
    else
      fatal "Fail: Apache should not be configured"
    fi

    logtest "Install with Apache and then disable"
    install3
    echo "Disabling apache via dpkg-reconfigure"
    (
        echo "linotp linotp/apache/activate boolean false"
        echo "linotp  linotp/dbconfig-reinstall boolean false"
    ) | $sudo debconf-set-selections
    dpkg_reconfigure
    $sudo service apache2 reload
    if ! wget -nv --user=admin --password=admin -O /dev/null --no-check-certificate https://localhost/manage; then
      echo "manage interface is unavailable as expected"
    else
      fatal "Fail: Apache should not be configured"
    fi
}


if [ ! -d "$linotpsrc" ]; then
    error "Linotp source directory not found: $linotpsrc"
    exit 1
fi

# Main command processing
if [ "$#" = 0 ]; then
    show_help
elif [ "$1" == "--help" ]; then
    show_help
elif [[ "$1" =~ ^(upgrade2to3|install3|upgrade3|mysql_password|install3psql|selenium_check|htpasswd|noapache|3reinstall)$ ]]
  then
    # Run the function with the same name as the command line argument
    $1
elif [ "$1" = "3upgrade" ]; then
    logtest "Upgrading to LinOTP 3"
    preseed_3
    install_3
    check_3
elif [ "$1" = "remove" ]; then
    purge
elif [ "$1" = "install2" ]; then
    purge
    logtest "Install linotp 2"
    preseed_2
    install_2 "$linotp2_deb_url"
    check_2
    selenium_check
elif [ "$1" = "alltests" ]; then
    install3
    selenium_check
    upgrade2to3
    selenium_check
    mysql_password
    install3psql
    selenium_check
    htpasswd
    noapache
    3reinstall
else
    show_help
fi

if [ -n "$have_errors" ]; then
    echo "Errors found"
    exit 1
fi
