# Note: If you want to run the tests against Firefox,
# change SELENIUM_DRIVER to `firefox`
# and use the firefox image in the selenium service.

services:
  runner:
    build:
      context: .
      dockerfile: docker/Dockerfile.linotp
      target: testenv
    environment:
      - LINOTP_HOST=linotp
      - LINOTP_PORT=5000
      - LINOTP_PROTOCOL=http
      - LINOTP_USERNAME=admin
      - LINOTP_PASSWORD=admin
      - HEALTHCHECK_PORT=80
      - SELENIUM_DRIVER=chrome
      - SELENIUM_PROTOCOL=http
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - PYTESTARGS=
    volumes:
      - ./linotp:/app/linotp:ro
      # - ./Screenshots:/app/linotp/tests/integration/Screenshots
    working_dir: /app/linotp/tests/integration
    depends_on:
      - linotp
      - selenium
      - blackdog-ldap
      - blackdog-mysql
    networks:
      - linotp-net
    command:
      - /bin/bash
      - -c
      - |
        /usr/local/bin/dockerfy \
        --template docker_cfg.ini.tmpl:/tmp/server_cfg.ini \
        --wait tcp://$$SELENIUM_HOST:$$SELENIUM_PORT \
        --timeout 60m \
        --wait tcp://$$LINOTP_HOST:$$LINOTP_PORT \
        --timeout 60m
        make integrationtests TCFILE=/tmp/server_cfg.ini PYTESTARGS="$$PYTESTARGS"

  linotp:
    build:
      context: .
      dockerfile: docker/Dockerfile.linotp
      target: testimg
    environment:
      - LINOTP_ADMIN_PASSWORD=admin
      - LINOTP_LOG_LEVEL=INFO
      - LINOTP_SESSION_COOKIE_SECURE=false
      - LINOTP_DISABLE_CONTROLLERS=gettoken
      - LINOTP_SITE_ROOT_REDIRECT=
      - LINOTP_DB_HOST=db
      - LINOTP_DB_PORT=5432
      - LINOTP_DB_WAITTIME=10s
      - LINOTP_DATABASE_URI=postgresql://linotp:linotppass@db/linotp_db #gitleaks:allow
      - LINOTP_PYTEST_DATABASE_URI=postgresql://linotp:linotppass@db/linotp_db #gitleaks:allow
    command: ["--with-bootstrap"]
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - linotp-net

  selenium:
    # Note: after 4.30.0-20250323 Chrome will throw a popup "Change your password" when they found it in a data breach.
    # This popup can't currently be disabled or intercepted -> breaking some tests.
    # What's making it even worse: That popup is not shown in the Screenshots taken by the tests. (But you can see it via VNC)
    # We should check if this is fixed in upcoming versions from time to time.
    image: selenium/standalone-chrome:4.30.0-20250323
    # image for firefox:
    # image: selenium/standalone-firefox:latest
    # known workaround to avoid the browser crashing inside a docker container
    # https://github.com/seleniumhq/docker-selenium/?tab=readme-ov-file#--shm-size2g
    shm_size: "2gb"
    # disable VNC password (otherwise: secret)
    environment:
      - SE_VNC_NO_PASSWORD=true
    ports:
      - "4444:4444"
      - "5900:5900" # port for debugging via VNC viewer
      - "7900:7900" # port for debugging via browser: http://localhost:7900
    networks:
      - linotp-net

  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=linotp_db
      - POSTGRES_USER=linotp
      - POSTGRES_PASSWORD=linotppass
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - linotp-net

  blackdog-ldap:
    image: gitbox.corp.linotp.de:5050/docker-images/blackdog-ldap/blackdog-ldap:latest
    networks:
      - linotp-net

  blackdog-mysql:
    image: gitbox.corp.linotp.de:5050/docker-images/blackdog-mysql/blackdog-mysql:latest
    networks:
      - linotp-net

networks:
  linotp-net:
    driver: bridge
