FROM python:3.7-buster AS base

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    libldap2-dev \
    libsasl2-dev \
    ldap-utils \
    libsodium-dev \
    # to check if given DB is available
    netcat-openbsd 

RUN useradd -ms /bin/bash tester && echo "root:Test123!\ntester:Test123!" | chpasswd

COPY ./ ./
RUN pip3 install -r requirements-test.txt \
    && pip install .

USER tester