.\" Manpage for linotp.
.\" Copyright (c) 2020 arxes-tolina GmbH

.TH linotp-create-enckey 1 "10 Aug 2020" "3.0" "LinOTP"

.SH NAME
linotp-create-enckey \- create an encryption key to protect sensitive LinOTP
data

.SH SYNOPSIS
\fIlinotp create-enckey\fR -f <ini file>

.SH DESCRIPTION
This command creates an encryption key for LinOTP. It reads the configuration
from the linotp.ini file to determine where the encryption key should be generated.

.SH COMMON OPTIONS

.PP
\fB\-f <ini file> \fR
.RS 4
The linotp.ini file containing the information where the encryption key is located.
.RE

.PP
\fB\-h\fR
.RS 4
Display a help message.
.RE

.SH SEE ALSO
\fBlinotp\fR(1), \fBlinotp-backup\fR(1), \fBlinotp-restore\fR(1)

.SH INTERNET SOURCES
https://www.linotp.org
