.\" Manpage for linotp.
.\" Copyright (c) 2020 arxes-tolina GmbH

.TH linotp-restore 1 "10 Aug 2020" "3.0" "LinOTP"

.SH NAME
linotp-restore \- restore a backup that was made with linotp-backup

.SH SYNOPSIS
\fIlinotp restore\fR <sql-dump-file> <encKey-File>

.SH DESCRIPTION
This tool can restore a previous made backup. You need to pass the SQL Dumpfile and the encryption key.

.SH COMMON OPTIONS

.PP
\fB\<sql-dump-file>\fR
.RS 4
The MySQL dump.
.RE

.PP
\fB\<encKey-File>\fR
.RS 4
The encryption key file.
.RE

.SH SEE ALSO
\fBlinotp\fR(1), \fBlinotp-backup\fR(1), \fBlinotp-enckey\fR(1)

.SH INTERNET SOURCES
https://www.linotp.org