.\" Manpage for linotp.
.\" Copyright (c) 2020 arxes-tolina GmbH

.TH linotp-sql-janitor 1 "10 Aug 2020" "3.0" "LinOTP"

.SH NAME
linotp-sql-janitor \- remove old entries from the audit table.

.SH SYNOPSIS
\fIlinotp sql-janitor\fR [--high=<high watermark>] [--low=<low watermark>]

.SH DESCRIPTION
This tool removes old entries from the audit table. If more than "high watermark" entries are in the audit table, older entries will be deleted so that only "low watermark"
entries remain in the table. 
This tool can decrypt the OTP Key stored in the LinOTP database. You need to pass the encrypted key, the IV and the filename of the encryption key.

.SH COMMON OPTIONS

.PP
\fB\--high=<high watermark>\fR
.RS 4
The maximum entries. If not given, 10.000 as default is assumed.
.RE

.PP
\fB\--low=<low watermark>\fR
.RS 4
The minimum old remaining entries. If not given 5.000 as default is assumed.
.RE

.SH SEE ALSO
\fBlinotp\fR(1)

.SH INTERNET SOURCES
https://www.linotp.org