.\" Manpage for linotp.
.\" Copyright (c) 2020 arxes-tolina GmbH

.TH linotp-backup 1 "10 Aug 2020" "3.0" "LinOTP"

.SH NAME
linotp-backup \- Backup LinOTP data.

.SH SYNOPSIS
\fIlinotp backup\fR

.SH DESCRIPTION
This command backs up the LinOTP database and encryption key. It creates a GPG
encrypted file to protect sensitive data. The database backup information is
taken from the linotp.ini file.

.SH SEE ALSO
\fBlinotp\fR(1), \fBlinotp-enckey\fR(1), \fBlinotp-restore\fR(1)

.SH INTERNET SOURCES
https://www.linotp.org