.\" Manpage for glinotpadm.py.
.\" Contact linotp@lsexperts.de for any feedback.
.TH man 1 "21 Sep 2010" "2.2" "glinotpadm.py man page"
.SH NAME
glinotpadm.py \- manage the LSE LinOTP server and OTP tokens.
.SH SYNOPSIS
glinotpadm.py 
.SH DESCRIPTION
glinotpadm.py is the graphical (python GTK based) client to manage the LSE LinOTP server. The LinOTP server is a authentication backend, that can handle many different OTP (one time password) tokens. The command takes no arguments. After starting the client, be sure to configure the LinOTP server you want to connect to. Therefor enter the menu Configuration->Client Configuration.


.SH INTERNET SOURCES
http://www.linotp.org,  http://www.lsexperts.de
.SH SEE ALSO
python (1)
.SH BUGS
No known bugs.
.SH AUTHOR
LSE Leading Security Experts GmbH <linotp@lsexperts.de>
