#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#    LinOTP - the open source solution for two factor authentication
#    Copyright (C) 2010 - 2016 LSE Leading Security Experts GmbH
#
#    This file is part of LinOTP server.
#
#    This program is free software: you can redistribute it and/or
#    modify it under the terms of the GNU Affero General Public
#    License, version 3, as published by the Free Software Foundation.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the
#               GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
#    E-mail: linotp@lsexperts.de
#    Contact: www.linotp.org
#    Support: www.lsexperts.de
#


VERSION = '0.1'
import os, sys
from getopt import getopt, GetoptError
import ConfigParser
from base64 import b64encode

from pysodium import crypto_scalarmult_curve25519_base as calc_dh_base

def usage():
    print  '''
    Parameter:
    -f <linotp.ini file>
    -h : help
    '''


def create_key_pair(config_file):

    print "Creating encryption key pair..."

    config_file = os.path.basename(config_file)
    config_path = os.path.abspath(os.path.dirname(config_file))
    config = ConfigParser.ConfigParser()
    config.read(config_file)
    config.set("DEFAULT", "here", config_path)

    secret_key_file = config.get('DEFAULT', 'linotpQrTokenSecretKeyFile')
    secret_key = os.urandom(32)

    with open(secret_key_file, 'w+') as f:
        f.write(b'qrtokensk:' + b64encode(secret_key))

    public_key_file = config.get('DEFAULT', 'linotpQrTokenPublicKeyFile')
    public_key = calc_dh_base(secret_key)

    with open(public_key_file, 'w+') as f:
        f.write(b'qrtokenpk:' + b64encode(public_key))

    print 'generated key pair! secret:%s, public:%s' % \
          (secret_key_file, public_key_file)



def main():

    config_file = ""
    try:
        opts, args = getopt(sys.argv[1:], "f:", ["file="])

    except GetoptError:
        print "There is an error in your parameter syntax:"
        usage()
        sys.exit(1)

    for opt, arg in opts:
        if opt in ('-f', '--file'):
            config_file = arg
        elif opt in ('-h', '--help'):
            usage()
            sys.exit(1)

    if config_file:
        create_key_pair(config_file)
    else:
        usage()
        sys.exit(2)

if __name__ == '__main__':
    main()
