.\" Manpage for linotp-token-usage
.\" Contact linotp@lsexperts.de for any feedback.
.TH man 1 "04 Feb 2013" "2.6" "linotp-token-usage man page"
.SH NAME
linotp-token-usage \- print the token usage from the token database.
.SH SYNOPSIS
linotp-token-usage
.SH DESCRIPTION
This tool reads the token number from the token database and also the token maximum and average for the last month 
from the audit trail.

.SH COMMON OPTIONS
None



.SH INTERNET SOURCES
http://www.linotp.org,  http://www.lsexperts.de
.SH SEE ALSO

linotpadm (1)

.SH BUGS
No known bugs.
.SH AUTHOR
LSE Leading Security Experts GmbH <linotp@lsexperts.de>
