.\"  LinOTP - the open source solution for two factor authentication
.\"  Copyright (C) 2010 - 2016 LSE Leading Security Experts GmbH
.\"
.\"  This file is part of LinOTP server.
.\"
.\"  This program is free software: you can redistribute it and/or
.\"  modify it under the terms of the GNU Affero General Public
.\"  License, version 3, as published by the Free Software Foundation.
.\"
.\"  This program is distributed in the hope that it will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU Affero General Public License for more details.
.\"
.\"  You should have received a copy of the
.\"             GNU Affero General Public License
.\"  along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\"
.\"  E-mail: linotp@lsexperts.de
.\"  Contact: www.linotp.org
.\"  Support: www.lsexperts.de
.\"
.\" Manpage for linotp-create-database.
.\" Contact linotp@lsexperts.de for any feedback.
.TH LINOTP-CREATE-DATABASE 1 "09 Sep 2013" "2.6" "linotp-create-database man page"
.SH NAME
linotp-create-database \- creates the database and a database user.
.SH SYNOPSIS
linotp-create-database -f <ini file>
.SH DESCRIPTION
This tool creates the database and database user for LinOTP. 
It reads the configuration from the linotp.ini file
to determine the necessary values.

You need to provide user credentials with the rights to create a database.
.SH COMMON OPTIONS
.PP
\fB\-f <ini file> \fR
.RS 4
The linotp.ini file containing the information where the database should be created.
.RE

.PP
\fB\-h\fR
.RS 4
Display a help message.
.RE

.SH INTERNET SOURCES
http://www.linotp.org,  http://www.lsexperts.de
.SH SEE ALSO

.SH BUGS
No known bugs.
.SH AUTHOR
LSE Leading Security Experts GmbH <linotp-community@lsexperts.de>
