.\" Manpage for linotp-pip-update.
.\" Contact linotp@lsexperts.de for any feedback.
.TH LINOTP-PIP-UPDATE 1 "04 Feb 2013" "2.5" "linotp-pip-update man page"
.SH NAME
linotp-pip-update \- updates a pip installation, e.g. in a virtualenv.
.SH SYNOPSIS
linotp-convert-token [-f] [-f]
.SH DESCRIPTION
This tool updates all packages via pip install --update.
.SH COMMON OPTIONS
.PP
\fB\-f, --force \fR
.RS 4
Do not ask. Just do it.
.RE

.PP
\fB\-h, --help\fR
.RS 4
Display a help message.
.RE

.SH INTERNET SOURCES
http://www.linotp.org,  http://www.lsexperts.de
.SH SEE ALSO

.SH BUGS
No known bugs.
.SH AUTHOR
LSE Leading Security Experts GmbH <linotp-community@lsexperts.de>
