.\"  LinOTP - the open source solution for two factor authentication
.\"  Copyright (C) 2010 - 2016 LSE Leading Security Experts GmbH
.\"
.\"  This file is part of LinOTP server.
.\"
.\"  This program is free software: you can redistribute it and/or
.\"  modify it under the terms of the GNU Affero General Public
.\"  License, version 3, as published by the Free Software Foundation.
.\"
.\"  This program is distributed in the hope that it will be useful,
.\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"  GNU Affero General Public License for more details.
.\"
.\"  You should have received a copy of the
.\"             GNU Affero General Public License
.\"  along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\"
.\"  E-mail: linotp@lsexperts.de
.\"  Contact: www.linotp.org
.\"  Support: www.lsexperts.de
.\"
.\" Manpage for linotp-token-usage
.\" Contact linotp@lsexperts.de for any feedback.
.TH man 1 "04 Feb 2013" "2.6" "linotp-token-usage man page"
.SH NAME
linotp-token-usage \- print the token usage from the token database.
.SH SYNOPSIS
linotp-token-usage
.SH DESCRIPTION
This tool reads the token number from the token database and also the token maximum and average for the last month 
from the audit trail.

.SH COMMON OPTIONS
None



.SH INTERNET SOURCES
http://www.linotp.org,  http://www.lsexperts.de
.SH SEE ALSO

linotpadm (1)

.SH BUGS
No known bugs.
.SH AUTHOR
LSE Leading Security Experts GmbH <linotp@lsexperts.de>
