#
#    LinOTP - the open source solution for two factor authentication
#    Copyright (C) 2010-2019 KeyIdentity GmbH
#    Copyright (C) 2019-     netgo software GmbH
#
#    This file is an unsupported contribution to the LinOTP server.
#
#    This program is free software: you can redistribute it and/or
#    modify it under the terms of the GNU Affero General Public
#    License, version 3, as published by the Free Software Foundation.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the
#               GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
#    E-mail: info@linotp.de
#    Contact: www.linotp.org
#    Support: www.linotp.de
#

"""
Simple library for FIDO2/WebAuthn token enrollment in Python.
"""

import json
import ssl
import sys
from getpass import getpass

import httpx
from fido2.client import DefaultClientDataCollector, Fido2Client, UserInteraction
from fido2.hid import CtapHidDevice

USER_AGENT = (
    "linotp-fido2-enroll/" + sys.modules["fido2_enroll"].__dict__["__version__"]
)


class LinOTPError(Exception):
    def __init__(self, message: str) -> None:
        super().__init__(message)


class LinOTPClient:
    def __init__(self, base_url: str, ca_file: str, username: str, password: str):
        ctx = ssl.create_default_context(cafile=ca_file)
        headers = {
            "User-Agent": USER_AGENT,
        }
        self.httpx = httpx.Client(base_url=base_url, verify=ctx, headers=headers)
        self.credentials = {"username": username, "password": password}
        self.logged_in = False

    def login(self):
        response = self.httpx.post("/admin/login", data=self.credentials)
        jd = response.json()
        if not jd.get("result", {}).get("value"):
            raise LinOTPError(jd.get("detail", {}).get("message", "No message"))
        self.logged_in = True
        return self

    def authenticated(func):
        def wrapper(*args, **kwargs):
            client, url = args

            if "headers" not in kwargs:
                kwargs["headers"] = {}
            if token := client.httpx.cookies.get("csrf_access_token"):
                kwargs["headers"]["X-CSRF-TOKEN"] = token
            return func(client, url, **kwargs)

        return wrapper

    @authenticated
    def post(self, url, **kwargs):
        response = self.httpx.post(url, **kwargs)
        jd = response.json()

        if not (result := jd.get("result", {})).get("status"):
            msg = result.get("error", {}).get("message", "No message")
            raise LinOTPError(msg)

        return jd


class CliInteraction(UserInteraction):
    def __init__(self):
        self._pin = None

    def prompt_up(self):
        print("Please touch the FIDO2 authenticator device …")

    def request_pin(self, permissions, rd_id):
        if not self._pin:
            self._pin = getpass("Enter FIDO2 authenticator PIN: ")
        return self._pin

    def request_uv(self, permissions, rd_id):
        print("User verification required.")
        return True


def _get_client(predicate=None, rp_id="", **kwargs):
    """Locate a CTAP device."""
    # This has been pinched from the fido2 examples.

    client_data_collector = DefaultClientDataCollector("https://" + rp_id)
    user_interaction = kwargs.pop("user_interaction", None) or CliInteraction()

    for dev in CtapHidDevice.list_devices():  # USB only for now
        client = Fido2Client(
            dev,
            client_data_collector=client_data_collector,
            user_interaction=user_interaction,
            **kwargs,
        )
        if predicate is None or predicate(client.info):
            return client
    msg = "No suitable FIDO2 authenticator found!"
    raise LinOTPError(msg)


def enroll_token(
    user: str,
    realm: str = "",
    base_url: str = "",
    ca_file: str = "/etc/ssl/certs/ca-certificates.crt",
    admin_user: str = "",
    admin_password: str = "",
    pair: bool = True,
    verbose: bool = False,
    description: str = "Generated by " + USER_AGENT,
) -> str:
    """Enroll a single FIDO2 token for `user`@`realm`."""

    if not admin_user or not admin_password:
        msg = "Need admin username and password to interact with LinOTP."
        raise LinOTPError(msg)

    linotp = LinOTPClient(
        base_url=base_url,
        ca_file=ca_file,
        username=admin_user,
        password=admin_password,
    ).login()

    # Start the enrollment inside LinOTP. This creates a new token and
    # gives us a challenge so we can pair an authenticator with the
    # token (which we don't have to, but still).

    jd = linotp.post(
        "/admin/init",
        data={
            "type": "fido2",
            "user": user,
            "realm": realm,
            "description": description,
        },
    )

    # Check for proper content in the response
    detail = jd.get("detail", {})
    serial = detail.get("serial", "<no serial>")
    if (reg_req := detail.get("registerrequest")) is None:
        msg = "Something's wrong - `registerrequest` is empty in /admin/init reply"
        raise LinOTPError(msg)

    if (rp_id := reg_req.get("rp", {}).get("id")) is None:
        msg = "Something's wrong - `registerrequest` has no RP ID`"
        raise LinOTPError(msg)

    if not pair:
        if verbose:
            print(
                f"The token {serial} has been created "
                "but must still be paired with a FIDO2 authenticator."
            )
        return

    # `Fido2Client` expects the timeout to be given in milliseconds.
    if (timeout := reg_req.get("timeout")) is not None:
        reg_req["timeout"] = int(timeout) * 1000

    # Make a credential inside the authenticator. (This would
    # otherwise be organised by the web browser.)

    if verbose:
        print(f"Pairing FIDO2 authenticator for token {serial} ({user}@{realm})")

    fido2_client = _get_client(rp_id=rp_id)
    fido2_credential = fido2_client.make_credential(reg_req)

    # Continue the enrollment inside LinOTP. This checks a potential
    # attestation for the authenticator and sets the (LinOTP-side)
    # token to “active”.

    jd = linotp.post(
        "/admin/init",
        data={
            "type": "fido2",
            "serial": serial,
            "attestationResponse": json.dumps(dict(fido2_credential)),
            "user": user,
            "realm": realm,
        },
    )

    if verbose:
        print(f"Token {serial} successfully rolled out for {user}@{realm}.")

    return serial
