#!/bin/bash
#
# Copy distribution packages from $DIST to $DIST-golden.
# This usually happens when the commit in question has a `release/*` tag,
# but it is the caller's responsibility to ensure this. It will be of no
# conceivable interest to you whatsoever unless you're doing official
# LinOTP development.
#
# This command is called with the desired base distribution (e.g., `buster`)
# and the names of one or more *.changes files – usually produced as Gitlab
# CI/CD artifacts – as parameters.
# We get the actual distribution and package names from the changes file.

WANTED_DIST=$1
GOLDEN_DIST=$1-golden
shift

declare -a PKGS	 # List of packages to be copied
for chf do
    PKG=$(sed -ne '/^Binary:/{s/^.*: //p;q}' $chf)         # Find package name
    DIST=$(sed -ne '/^Distribution:/{s/^.*: //p;q}' $chf)  # Find distribution name
    if [ -z "$DIST" ]; then
	echo >&2 "E:Couldn't find 'Distribution:' line in $chf, skipping"
	continue
    elif [ -z "$PKG" ]; then
	echo >&2 "E:Couldn't find 'Binary:' line in $chf, skipping"
	continue
    fi
    echo >&2 "I:Considering $PKG ($chf)"
    if [ "$DIST" != "$WANTED_DIST" ]; then
    	echo >&2 "W:$PKG's distribution is $DIST, not $WANTED_DIST, skipping"
    	continue
    fi
    PKGS+=($PKG)
done

if [ "${#PKGS[*]}" -gt 0 ]; then # Do we have work to do?
    echo >&2 "I:Copying ${PKGS[@]} to ${GOLDEN_DIST}"
    ssh dists@$DEV_REPO_HOST reprepro copy ${GOLDEN_DIST} ${WANTED_DIST} ${PKGS[@]}
    EXITCODE=$?
    echo >&2 "I:Done"
else
    echo >&2 "I:Nothing to do"
    EXITCODE=0
fi

exit $EXITCODE
