#!/bin/sh

# This script ensures that the package version is appropriate
# for the distribution that we are building for.
#
# = Snapshot builds =
# We use git-buildpackage's dch subcommand to generate a changelog
# containing git commit information. While not as good as a hand
# edited changelog, it contains enough information to help testers
# understand which changes are contained in the package.
#
# We use gbp-dch to set a version number based on the commit date
# and git commit id.
#
# = Building from tags =
# If we are building for a tag, we generate final release packages:
#   * Leave the changelog entries as they are
#   * If a backport, generate a backport changelog entry
#
# = Distribution flag =
# In all cases, we want to make sure that the distribution name
# is set. This is to ensure that reprepro assigns the package to
# the correct distribution. We determine the distribution
# using lsb_release.

if [ -n "$1" ]
  then
    # The debian directory is in another directory
    DEBIAN_DIR=$1
    if [ ! -d "$DEBIAN_DIR" ]
      then
        echo Directory "$DEBIAN_DIR" not found
        exit 1
    fi
    GBP_SINCE_PARAM="-s $(git rev-list -1 HEAD $DEBIAN_DIR/debian/changelog)"
    export GIT_DIR=$(realpath .git)
    cd $DEBIAN_DIR
else
  DEBIAN_DIR=
  GBP_SINCE_PARAM="--auto"
fi

# Determine the release name and number that we are building for
DEBIAN_RELEASE_NAME="$(lsb_release -c -s)"

# Keep any suffix defined on the distribution name such as
#  buster-dev -> DISTRIBUTION_SUFFIX="-dev"
#
# We will use this to achieve a mapping such as
#  buster-dev -> squeeze-dev
# It will be left blank if there is no suffix
DISTRIBUTION_SUFFIX="$(dpkg-parsechangelog -S Distribution | sed -ne '/-/ s/^[a-z]\+\(-[a-z]\+\)$/\1/p')"

# Ensure generated changelog entries have the same
export DEBEMAIL="$(dpkg-parsechangelog -S Maintainer)"

# To ensure package version numbers for backports follow in the
# correct order, we treat stable / oldstable as a
# backport build
if [ "$DEBIAN_RELEASE_NAME" = bullseye ]; then
  BPO_FLAG=
else
  BPO_FLAG=--bpo
fi

# Are we building a snapshot or tag?
if [ ! -n "${CI_COMMIT_TAG}" ]; then
  # Snapshot build

  # install git-buildpackage
  which gbp || apt-get install -y --no-install-recommends git-buildpackage

  COMMIT_TS=$(git show -s --pretty=format:%ct HEAD)
  COMMIT_DATE=$(date --date="@${COMMIT_TS}" +%Y%m%d%H%M)
  CURRENT_VERSION="$(dpkg-parsechangelog -S Version)"

  gbp dch $GBP_SINCE_PARAM --snapshot --snapshot-number="${COMMIT_DATE}" --no-multimaint --ignore-branch $BPO_FLAG
else
  # Tagged build

  # Only create a changelog entry if we are creating a backport version
  if [ -n "$BPO_FLAG" ]; then
    dch --bpo "Autobuilt by CI"
  fi
fi

# In order to upload to our internal archive, we need to set the distribution to
# correct destination distribution
CURRENT_DISTRIBUTION="$(dpkg-parsechangelog -S Distribution)"
sed "1s/ ${CURRENT_DISTRIBUTION}\(; urgency=\)/ ${DEBIAN_RELEASE_NAME}${DISTRIBUTION_SUFFIX}\1/" -i debian/changelog

# Show the results
dpkg-parsechangelog
